### ISSUE TITLE
Problems in Plan

### ISSUE THREAD

**Issue by tplive** [jamesrcounts/terraform-getting-started-azure#5]
Hi James!
I found your excellent article on safe terraform pipelines, and I'm trying to reimplement one of our pipelines with your excellent guidance. I've gotten as far as the Plan step, deploying our existing tf code "as-is", but it fails with an error message I cannot comprehend or get around, and I was hoping you could help me out?

The redacted log looks like this:
```
Starting: Terraform Plan
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.189.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/a1d29cea-636a-4af7-a1c3-c10f52c3d0f7.sh
module.azurerm_virtual_machine_d_runners.tls_private_key.ssh[0]: Refreshing state... [id=3XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX8]
module.azurerm_virtual_machine_t_runners.tls_private_key.ssh[0]: Refreshing state... [id=bXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXe]
module.azurerm_virtual_machine_p_runners.tls_private_key.ssh[1]: Refreshing state... [id=cXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX6]
module.azurerm_virtual_machine_p_runners.tls_private_key.ssh[0]: Refreshing state... [id=7XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXb]
module.azurerm_virtual_machine_t_runners.tls_private_key.ssh[1]: Refreshing state... [id=eXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXe]
╷
│ Error: Insufficient features blocks
│ 
│   on <empty> line 0:
│   (source code not available)
│ 
│ At least 1 "features" blocks are required.
╵
##[error]Bash exited with code '1'.
Finishing: Terraform Plan

```

I've already checked my main.tf, and it contains the provider with a features block:
```
provider "azurerm" {
  features {}
}
```

...but the azure_virtual_machine_*_runners module referenced above also needs a couple of other providers (hashicorp/random and hashicorp/tls) so I thought they might have to be added as well, but that didn't help.. :/

Do you know what causes this? As previously stated, our original pipeline setup deploys this TF code without issue, so I'm lost here... 😅

Thank you for your great work!

Thomas

**Comment by jamesrcounts** [comment]
Sorry for the late response but unfortunately I have only ever seen this error related to the azurerm provider, which you already seem to be aware of.  Did you ever figure this out?

**Comment by tplive** [comment]
Hi James! I had forgotten about this issue, sorry! Yes we figured it out somehow, I forget what the solution was, but I think it was unrelated to your setup. I will close the issue.
