### ISSUE TITLE
Terraform PIN | Timeout

### ISSUE THREAD

**Issue by florian-ried** [jamesrcounts/terraform-getting-started-azure#7]
Hi @jamesrcounts 

thank you very much for the great code.
I have the problem that the pipeline times out after 60 minutes at the "Pin Terraform" step. Unfortunately without errors. Do you have an idea what it could be?

![image](https://user-images.githubusercontent.com/95634472/216671654-744a36e9-67e4-44db-95e5-bbee30192a7b.png)

![image](https://user-images.githubusercontent.com/95634472/216671696-8f3d4115-7e57-4e41-a257-2e553d601a2f.png)

Thanks in advance :)

**Comment by jamesrcounts** [comment]
I've actually never seen this before.  I assume the behavior is consistent?  You could try adding the -x option here: https://github.com/jamesrcounts/terraform-getting-started-azure/blob/1e3ecae503f73c31d89a14fdc283986fceae4c17/pipeline-templates/pin-terraform.yml#L7

This should print out each command as it executes and might provide some clues.  Let me know what you find out!

**Comment by florian-ried** [comment]
Many thanks for the quick response @jamesrcounts 
The problem occurs consistently, right.
I added the x parameter. The pipeline has been running for more than 5 minutes since then, with no further error output. I also tried it with an older version of Terraform. With the same error...
